Elias/issue#7/menu styling when onpage
508-dev/508.dev pull request #25
Opened 2023-04-17 21:27 UTC by Figgy24-20

issue #7 

Nav items have new class="on-page" which styles the links blue when on a given page. 
on-page also styles them to have a dark red #1e0d0a shadow

2023-04-28 09:08 UTC, komali2 requested changes

2023-04-28 09:08 UTC, komali2 commented on src/css/style.css
> +  color: #92dce5;
ideally colors are always variables, at line `8` see the variables defined at `:root`. This also means all colors will be within the palette we chose a bit back.

2023-04-28 09:08 UTC, komali2 commented on src/css/style.css
> +  color: #92dce5;
Thus yeah this color isn't in the palette so I feel like it doesn't quite match:
![2023-04-28_17-06](https://user-images.githubusercontent.com/8533113/235105567-32f32840-4e52-43c6-9e3a-e76941bc5f72.png)

2023-04-28 09:08 UTC, komali2 commented on src/css/style.css
> +  text-shadow: 2px 2px 3px #1e0d0a;
as for the text shadow, kinda nice, but again same comment regarding color that isn't a predefined variable. Also, I find this drop shadow makes it a bit difficult to read, the top left of all the letters are like, white or something, idk, but it's not very contrasty

A pure color change alone is probably enough to accomplish our goal of letting the user know which page they're on. our page is really flat with no other places that have drop shadows. If we do use them, i think it makes more stylistic sense to start using them on concepts like Cards (see https://m3.material.io/)

Oh, or perhaps changing the underline type, plus the color, bearing in mind that for colorblind users a color change alone isn't quite enough

2023-04-28 09:08 UTC, komali2 commented on src/engineering.html
> +            <li><a href="engineering.html" class="on-page" >Engineer</a></li>
this strategy is perfectly acceptable and how i would have done it

2023-04-30 02:20 UTC, Figgy24-20 commented on src/css/style.css
> +  text-shadow: 2px 2px 3px #1e0d0a;
Sure I'll switch it to variables, and make a more matching color. Just to you know, the color I used is from the color palate linked at the top of the css.

2024-01-25 04:47 UTC, closed without merging